'use strict';
const API='https://spy0dte-live-backend-v2.vercel.app/api/signal';
const $=id=>document.getElementById(id);
const fmt=(v,n=2)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(n):'—';
const labels={'CALL BUY':'CALL買い条件成立','PUT BUY':'PUT買い条件成立','WAIT':'待機','NO TRADE':'見送り','DATA ERROR':'判定不可','CLOSED':'市場時間外'};
let pending=null, expiryTimer=null, buttonTimer=null, result=null, blockedUntil=0, requestGeneration=0;
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function clearValidity(){clearTimeout(expiryTimer);expiryTimer=null;}
function expire(){if(!result)return;$('freshness').textContent='取得時点の結果です。価格の有効期限を過ぎたため、注文前に再判定してください。';document.querySelectorAll('[data-buy]').forEach(n=>{n.textContent='取得時は買い条件成立／現在は再判定が必要';});$('headline').textContent='取得時の判定結果';}
function candidate(r){const side=r.side||'候補',o=r.option||{};const card=el('article',undefined,'candidate '+side.toLowerCase());card.append(el('div',side+' $'+(Number.isFinite(o.strike)?fmt(o.strike,Number.isInteger(o.strike)?0:2):'—'),'contract'));card.append(el('div',o.expiration?'満期 '+o.expiration:'当日満期の契約を確認中','muted'));card.append(el('div','買い判断','score-label'));const score=el('div',r.score==null?'判定不可':String(r.score),'score');if(r.score!=null)score.append(el('small','%'));card.append(score);const meter=el('div',undefined,'meter'),bar=el('span');bar.style.width=Math.max(0,Math.min(100,r.score||0))+'%';meter.append(bar);card.append(meter);const state=el('div',labels[r.decision]||'判定不可','state');if(r.buyReady)state.dataset.buy='true';card.append(state);card.append(el('p','1枚の目安 '+(o.premiumPerContract!=null?'$'+fmt(o.premiumPerContract):'—'),'money'));card.append(el('p','Bid $'+fmt(o.bid)+' / Ask $'+fmt(o.ask)+' · スプレッド '+fmt(o.spreadPct,1)+'%','muted'));const list=el('ul',undefined,'reasons');for(const reason of r.reasons||[])list.append(el('li',reason));card.append(list);if(r.invalidation!=null)card.append(el('p','SPYの撤退検討目安 $'+fmt(r.invalidation)+'（オプション価格ではありません）','muted'));if(r.scoreChecks){const details=el('details');details.append(el('summary','スコアの内訳'));const checks=el('ul',undefined,'reasons');for(const c of r.scoreChecks)checks.append(el('li',(c.passed?'✓ ':'— ')+c.label+' '+(c.passed?c.weight:0)+'/'+c.weight));details.append(checks);card.append(details);}return card;}
function draw(bars){const canvas=$('chart'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,800,250);if(!bars?.length)return;const min=Math.min(...bars.map(b=>b.low)),max=Math.max(...bars.map(b=>b.high)),span=max-min||1,xstep=760/bars.length,y=p=>225-(p-min)/span*200;ctx.strokeStyle='#293748';for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(20,25+i*65);ctx.lineTo(780,25+i*65);ctx.stroke();}bars.forEach((b,i)=>{const x=20+(i+.5)*xstep;ctx.strokeStyle=ctx.fillStyle=b.close>=b.open?'#90e4c0':'#ed959d';ctx.beginPath();ctx.moveTo(x,y(b.high));ctx.lineTo(x,y(b.low));ctx.stroke();ctx.fillRect(x-Math.max(1,xstep*.3),Math.min(y(b.open),y(b.close)),Math.max(2,xstep*.6),Math.max(1,Math.abs(y(b.close)-y(b.open))));});}
function render(r,rtt){result=r;clearValidity();$('result').hidden=false;$('headline').textContent=labels[r.decision]||'判定結果';$('asof').textContent='取得 '+new Date(r.serverTime).toLocaleTimeString('ja-JP');$('summary').textContent=(r.reasons||[]).join('／');$('spot').textContent='$'+fmt(r.spy);$('candidates').replaceChildren(...(r.candidates||[]).map(candidate));const f=r.indicators||{};$('indicators').replaceChildren();for(const [name,value] of [['VWAP',fmt(f.vwap)],['EMA9 / EMA21',fmt(f.ema9)+' / '+fmt(f.ema21)],['出来高 / 直近20本平均',fmt(f.volumeRatio20)+'倍'],['直近5本 高値 / 安値',fmt(f.recentHigh)+' / '+fmt(f.recentLow)],['ATR14・1分足',fmt(f.atr14,3)]])$('indicators').append(el('dt',name),el('dd',value));draw(r.chart);const validity=Date.parse(r.validUntil)-Date.parse(r.serverTime)-rtt;if(r.buyReady&&validity>0){$('freshness').textContent='取得時点で買い条件成立。価格は変動します。';expiryTimer=setTimeout(expire,validity);}else if(r.buyReady)expire();else $('freshness').textContent='ボタンを押した時点の判定です。自動更新はしません。';}
async function judge(){if(pending||document.hidden||performance.now()<blockedUntil)return;const generation=++requestGeneration,controller=new AbortController();pending=controller;clearValidity();result=null;$('result').hidden=true;$('judge').disabled=true;$('judge').textContent='判定中…';$('progress').textContent='チャートとオプションチェーンを取得しています。';const start=performance.now();const timeout=setTimeout(()=>controller.abort(),55000);let cooldown=10000;try{const response=await fetch(API,{cache:'no-store',signal:controller.signal});const data=await response.json();if(generation!==requestGeneration||document.hidden)return;if(!response.ok||data.ok!==true||data.mode!=='INDICATOR_ONLY'){cooldown=Math.max(10000,Math.min(60000,(Number(data.retryAfterSeconds)||60)*1000));throw Error(data.error||'最新データを取得できません');}render(data,performance.now()-start);$('progress').textContent='判定が完了しました。次の取得はボタンを押したときだけです。';}catch(e){if(generation!==requestGeneration||document.hidden)return;$('progress').textContent='判定不可：'+(e.name==='AbortError'?'通信がタイムアウトしました':e.message)+'。時間をおいて再判定してください。';cooldown=60000;}finally{clearTimeout(timeout);if(pending===controller)pending=null;blockedUntil=performance.now()+cooldown;$('judge').textContent='もう一度判定する';clearTimeout(buttonTimer);buttonTimer=setTimeout(()=>{$('judge').disabled=false;},cooldown);}}
$('judge').addEventListener('click',judge);
function suspend(){requestGeneration++;pending?.abort();clearValidity();expire();}
document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});window.addEventListener('pagehide',suspend);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
