const fs=require('fs'),assert=require('assert/strict'),{JSDOM}=require('jsdom');
const dom=new JSDOM(fs.readFileSync('paper.html','utf8'),{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;
w.AbortSignal={timeout:()=>undefined};w.setTimeout=()=>1;
w.fetch=async()=>({ok:true,status:200,json:async()=>({adminConfigured:true})});
w.eval(fs.readFileSync('paper.js','utf8')+'\nwindow.render=showIndicatorAnalysis;window.sync=syncAccounts;');
w.render({decisionClass:'SYSTEM_NOT_READY',features:{},reasons:['NO_CLOSED_BARS']},null,false);
let text=w.document.getElementById('indicatorAnalysis').textContent;
assert.match(text,/市場時間外・予定休止/);assert.doesNotMatch(text,/SYSTEM NOT READY|NO_CLOSED_BARS/);
w.render({decisionClass:'NO_TRADE',observedAt:'2026-09-30T18:00:00Z',features:{barCloseAt:'2026-09-30T18:00:00Z',trendSeed:{date:'2026-09-29',bars:78}},reasons:['TREND_NOT_ALIGNED']},null,false);
text=w.document.getElementById('indicatorAnalysis').textContent;
assert.match(text,/保存済みの市場中/);assert.match(text,/78本/);assert.match(text,/NO TRADE/);
w.render({decisionClass:'SESSION_WARMUP',features:{warmupUntil:'2026-09-30T14:15:00Z'},reasons:['SETUP_WINDOW_WARMUP']},null,true);
text=w.document.getElementById('indicatorAnalysis').textContent;
assert.match(text,/予定された待機/);assert.match(text,/45分/);assert.match(text,/最短時刻/);
const accounts={'V65_TREND_RETEST_1:STANDARD':{},'V65_TREND_RETEST_2:STANDARD':{}};
w.sync(accounts);const select=w.document.getElementById('account');assert.equal(select.value,'V65_TREND_RETEST_1:STANDARD','when main accounts are absent preserve access to supplied status without inventing accounts');
select.value='V65_TREND_RETEST_1:STANDARD';w.sync(accounts);assert.equal(select.value,'V65_TREND_RETEST_1:STANDARD');
assert.match(select.options[0].textContent,/追加インジ1/);assert.match(select.options[1].textContent,/厳格条件の比較用/);
accounts['V65_BALANCED_3:STANDARD']={};w.sync(accounts);assert.equal(select.value,'V65_TREND_RETEST_1:STANDARD','a newly discovered archived account cannot replace explicit selection');
w.render({strategy:'V65_BALANCED_3',features:{},reasons:[]},null,true,{session:'2026-10-01',observations:12,unique5mWindows:3,baselineBuyObservations:4,combinedSignalObservations:2,uniqueCombinedSignalWindows:1,requiredChecks:{coreTrend:{passCount:9,failCount:3,unavailableCount:0}},studyChecks:{retest:{passCount:0,failCount:12,unavailableCount:0}}});
text=w.document.getElementById('indicatorAnalysis').textContent;
assert.match(text,/バランス検証版/);assert.match(text,/約定件数ではありません/);assert.match(text,/比較用：押し戻り確認/);assert.match(text,/独立した取引件数/);
console.log('PASS: v2 selection, explicit legacy selection preserved, planned warmup, offhours separated and saved market evidence retained');
