const fs=require('fs'),assert=require('assert/strict'),{JSDOM}=require('jsdom');
const dom=new JSDOM(fs.readFileSync('paper.html','utf8'),{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;
w.AbortSignal={timeout:()=>undefined};w.setTimeout=()=>1;
w.fetch=async()=>({ok:true,status:200,json:async()=>({adminConfigured:true})});
w.eval(fs.readFileSync('paper.js','utf8')+'\nwindow.render=showIndicatorAnalysis;window.sync=syncAccounts;');
w.render({decisionClass:'SYSTEM_NOT_READY',features:{},reasons:['NO_CLOSED_BARS']},null,false);
let text=w.document.getElementById('indicatorAnalysis').textContent;
assert.match(text,/市場時間外・予定休止/);assert.doesNotMatch(text,/SYSTEM NOT READY|NO_CLOSED_BARS/);
w.render({decisionClass:'NO_TRADE',observedAt:'2026-09-30T18:00:00Z',features:{barCloseAt:'2026-09-30T18:00:00Z',trendSeed:{date:'2026-09-29',bars:78}},reasons:['TREND_NOT_ALIGNED']},null,false);
text=w.document.getElementById('indicatorAnalysis').textContent;
assert.match(text,/保存済みの市場中/);assert.match(text,/78本/);assert.match(text,/NO TRADE/);
w.render({decisionClass:'SESSION_WARMUP',features:{warmupUntil:'2026-09-30T14:15:00Z'},reasons:['SETUP_WINDOW_WARMUP']},null,true);
text=w.document.getElementById('indicatorAnalysis').textContent;
assert.match(text,/予定された待機/);assert.match(text,/45分/);assert.match(text,/最短時刻/);
const accounts={'V65_TREND_RETEST_1:STANDARD':{},'V65_TREND_RETEST_2:STANDARD':{}};
w.sync(accounts);const select=w.document.getElementById('account');assert.equal(select.value,'V65_TREND_RETEST_2:STANDARD');
select.value='V65_TREND_RETEST_1:STANDARD';w.sync(accounts);assert.equal(select.value,'V65_TREND_RETEST_1:STANDARD');
assert.match(select.options[0].textContent,/旧版/);assert.match(select.options[1].textContent,/前営業日から準備/);
console.log('PASS: v2 selection, explicit legacy selection preserved, planned warmup, offhours separated and saved market evidence retained');
