// DOM unit verification; no browser, live data, network or secret credentials.
const fs=require('fs'),assert=require('assert/strict'),{JSDOM}=require('jsdom');
const state=JSON.parse(fs.readFileSync('testdata/paper-synthetic-state.json','utf8'));
const html=fs.readFileSync('paper.html','utf8'),code=fs.readFileSync('paper.js','utf8');
const dom=new JSDOM(html,{url:'https://yoshiharu-art.github.io/spy0dte-v6/paper.html',runScripts:'outside-only'}),w=dom.window,calls=[];
const diagnosticFixture={coverage:{events_read:45,start_at:'2026-09-25T19:21:00Z',end_at:'2026-09-25T19:29:00Z'},accounts:{'V64_BASELINE_1:STANDARD':{latest_recorded_commit:{decisions:9,skips:9,reasons:{'<img src=x onerror=alert(1)>':1,STALE_QUOTE:8},data_blockers:{'spyPriceAt:STALE_SOURCE_TIME':6}},observed_window:{decisions:350,data_blocked_rate:.9}}}};
w.AbortSignal={timeout:()=>undefined};w.setTimeout=()=>1;w.clearTimeout=()=>{};
w.fetch=async(url,options={})=>{calls.push({url,options});return {ok:true,status:200,json:async()=>url.endsWith('health')?{release:'6.4-paper-auto-candidate-1',adminConfigured:true}:url.endsWith('diagnostics')?structuredClone(diagnosticFixture):url.endsWith('exit-review')?{coverage:{journal_events_read:10,older_events_may_be_omitted:false},trades_omitted:0,rows:[{account_id:'SYNTHETIC',trade_id:'<img src=x onerror=alert(1)>',status:'MISSING_OBSERVATION',official_net_cents:-700,hypothetical_net_cents:null,difference_cents:null,observed_at:null}]}:structuredClone(state)}};
w.eval(code+'\nwindow.__testShow=show;window.__testPoll=poll;');
(async()=>{
 await new Promise(setImmediate);assert.equal(calls.length,1);assert.equal(calls[0].options.method,undefined);
 w.document.getElementById('token').value='SYNTHETIC_SECRET_NOT_REAL';w.document.getElementById('connect').click();await new Promise(setImmediate);
 assert.equal(w.document.getElementById('token').value,'');assert.match(w.document.getElementById('cash').textContent,/9,993/);
 w.document.getElementById('review').click();await new Promise(setImmediate);
 assert.match(w.document.getElementById('exitReview').textContent,/観測不足/);
 assert.equal(w.document.querySelector('#exitReview img'),null);
 assert.equal(calls.find(x=>x.url.endsWith('exit-review')).options.method,undefined);
 assert.match(w.document.getElementById('cash').textContent,/9,993/);
 assert.match(w.document.getElementById('dataMode').textContent,/テスト/);assert.match(w.document.getElementById('history').textContent,/仮想約定/);
 assert.match(w.document.getElementById('news').textContent,/未確認/);assert.equal(w.document.querySelectorAll('#comparison tr').length,4);
 assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.length,0);assert(!w.document.body.textContent.includes('SYNTHETIC_SECRET_NOT_REAL'));
 w.document.getElementById('start').click();await new Promise(setImmediate);
 assert(calls.some(x=>x.url.endsWith('command')&&JSON.parse(x.options.body).command==='start'));
 assert(!calls.some(x=>x.url.endsWith('tick')));
 await w.__testPoll();assert(calls.at(-1).url.endsWith('status'));assert.equal(calls.at(-1).options.method,undefined);
 const monitored=structuredClone(state);monitored.operations={status:'STOPPED',last_save_at:'2026-09-24T17:03:00Z',last_interval_seconds:60,max_interval_seconds:70,total_failures:2,reason:'RUNNER_HEARTBEAT_MISSING'};w.__testShow(monitored);assert.match(w.document.getElementById('runtime').textContent,/停止/);assert.match(w.document.getElementById('operations').textContent,/60.0秒/);
 w.document.getElementById('pause').click();await new Promise(setImmediate);
 assert(calls.some(x=>x.url.endsWith('command')&&JSON.parse(x.options.body).command==='pause'));
 const malicious=structuredClone(state);malicious.accounts['V64_BASELINE_1:STANDARD'].last_reason='<img src=x onerror=alert(1)>';
 w.__testShow(malicious);assert.equal(w.document.querySelector('#reason img'),null);
 assert(calls.every(x=>x.url.startsWith('https://spy0dte-live-backend-v2.vercel.app/api/paper/')));
 assert(!/localStorage|sessionStorage|window\.open/.test(code));
 assert(!/submit_order|place_order|cancel_order|transfer_funds/.test(code));
 assert(!calls.some(x=>x.url.endsWith('tick')));
 const diagnosed=structuredClone(state);diagnosed.accounts['V64_BASELINE_1:STANDARD'].last_data_quality={checkedAt:'2026-09-24T17:00:00Z',realtimeState:'UNVERIFIED',haltState:'UNVERIFIED',fields:{volPriceAt:{label:'VIXY代理指標',status:'STALE_SOURCE_TIME',ageSeconds:230,maxAgeSeconds:60}}};w.__testShow(diagnosed);assert.match(w.document.getElementById('dataQuality').textContent,/230.0秒前/);assert.match(w.document.getElementById('dataQuality').textContent,/リアルタイム資格未確認/);assert.match(w.document.getElementById('qualityAt').textContent,/現在の気配ではありません/);
 const inactive=structuredClone(state);inactive.operations={status:'SCHEDULED_WAIT',reason:'NEXT_SCHEDULED_RUN',schedule:{next_expected_at:'2026-09-28T13:00:00Z'}};inactive.accounts['V64_BASELINE_1:STANDARD'].position=null;inactive.accounts['V64_BASELINE_1:STANDARD'].clock.marketOpen=false;w.__testShow(inactive);
 assert.match(w.document.getElementById('runtime').textContent,/次回の定期実行待ち/);assert.match(w.document.getElementById('updated').textContent,/予定休止中/);assert.match(w.document.getElementById('reason').textContent,/市場時間外/);assert.equal(w.document.getElementById('dataQuality').textContent,'');
 w.document.getElementById('diagnose').click();await new Promise(setImmediate);assert.match(w.document.getElementById('diagnostics').textContent,/判定 9回/);assert.match(w.document.getElementById('diagnostics').textContent,/SPY最終約定：古い \/ 6回/);assert.equal(w.document.querySelector('#diagnostics img'),null);assert.equal(calls.find(x=>x.url.endsWith('diagnostics')).options.method,undefined);
 const beforeClose=calls.length;w.dispatchEvent(new w.Event('pagehide'));await w.__testPoll();assert.equal(calls.length,beforeClose);
 console.log('PASS: PAPER DOM render, 4 accounts, TEST label, UNKNOWN news, start/pause server calls, read-only polling, no browser tick, stale status, page-close stops reads only, memory-only auth, XSS text rendering, no live order endpoints.');
})().catch(e=>{console.error(e);process.exitCode=1;});
